defaults:
  - _self_
  - problem: bpp_online
  - override hydra/output: local

hydra:
  job:
    chdir: True

# The chosen algorithm
algorithm: hsevo

# LLM parameters
model: 'gemini/gemini-2.5-flash'
# model: 'nvidia_nim/nvidia/llama-3.3-nemotron-super-49b-v1.5'
temperature: 1 # temperature for chat completion

# Main GA loop parameters
max_token: 250000
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 10 # initial population size for GA
mutation_rate: 0.5 # mutation rate for GA
timeout: 50 # timeout for evaluation of a single heuristic
warm_up: 0 

# Harmony search
hm_size: 5
hmcr: 0.7
par: 0.5
bandwidth: 0.2
max_iter: 5

# behavior descriptor
bd_list: ["SLOC", "cyclomatic_complexity"]
bd_step: [1, 1]